def generate_html():
    html_content = """<html>
<head>
<title>Hello World</title>
</head>
<body>
<h1>Hello World</h1>
<p>This is a simple Hello World HTML page generated by a Python script.</p>
</body>
</html>"""
    return html_content

if __name__ == "__main__":
    # Print the HTTP response headers
    print("HTTP/1.1 200 OK")
    print("Content-Type: text/html")
    print()  # Blank line to separate headers from the body

    # Print the HTML content
    print(generate_html())
